"""Task foundation package for pre-Gate-3 task assets and schemas."""

from roxauto.tasks.catalog import TaskFoundationRepository
from roxauto.tasks.models import (
    GoldenScreenshotCase,
    GoldenScreenshotConvention,
    TaskAssetInventory,
    TaskAssetKind,
    TaskAssetRecord,
    TaskAssetStatus,
    TaskBlueprint,
    TaskFixtureProfile,
    TaskGapDomain,
    TaskImplementationState,
    TaskInventory,
    TaskInventoryRecord,
    TaskPackCatalog,
    TaskPackCatalogEntry,
    TaskReadinessCollection,
    TaskReadinessReport,
    TaskReadinessRequirement,
    TaskReadinessState,
    TaskRuntimeBuilderInput,
    TaskStepBlueprint,
)

__all__ = [
    "GoldenScreenshotCase",
    "GoldenScreenshotConvention",
    "TaskAssetInventory",
    "TaskAssetKind",
    "TaskAssetRecord",
    "TaskAssetStatus",
    "TaskBlueprint",
    "TaskFixtureProfile",
    "TaskGapDomain",
    "TaskFoundationRepository",
    "TaskImplementationState",
    "TaskInventory",
    "TaskInventoryRecord",
    "TaskPackCatalog",
    "TaskPackCatalogEntry",
    "TaskReadinessCollection",
    "TaskReadinessReport",
    "TaskReadinessRequirement",
    "TaskReadinessState",
    "TaskRuntimeBuilderInput",
    "TaskStepBlueprint",
]

