"""GUI shell package."""

from roxauto.app.runtime_bridge import OperatorConsoleRuntimeBridge
from roxauto.app.viewmodels import (
    ClaimRewardsEditorView,
    ClaimRewardsPaneView,
    ClaimRewardsStepView,
    ConsoleSnapshot,
    ConsoleSummaryView,
    InstanceCardView,
    InstanceDetailView,
    InstanceListEntryView,
    LogEntryView,
    LogPaneView,
    ManualControlsView,
    OperatorConsoleState,
    QueueItemView,
    QueuePaneView,
    TaskReadinessPaneView,
    TaskReadinessRowView,
    build_console_snapshot,
    build_console_snapshot_from_runtime,
    build_console_summary,
    build_instance_list_rows,
    build_log_pane,
    build_manual_control_command,
    build_operator_console_state,
    build_task_readiness_pane,
)

__all__ = [
    "ClaimRewardsEditorView",
    "ClaimRewardsPaneView",
    "ClaimRewardsStepView",
    "ConsoleSnapshot",
    "ConsoleSummaryView",
    "InstanceCardView",
    "InstanceDetailView",
    "InstanceListEntryView",
    "LogEntryView",
    "LogPaneView",
    "ManualControlsView",
    "OperatorConsoleRuntimeBridge",
    "OperatorConsoleState",
    "QueueItemView",
    "QueuePaneView",
    "TaskReadinessPaneView",
    "TaskReadinessRowView",
    "build_console_snapshot",
    "build_console_snapshot_from_runtime",
    "build_console_summary",
    "build_instance_list_rows",
    "build_log_pane",
    "build_manual_control_command",
    "build_operator_console_state",
    "build_task_readiness_pane",
]
