"""GUI shell package."""

from roxauto.app.viewmodels import (
    AnchorInspectionView,
    CalibrationPaneView,
    ConsoleSnapshot,
    FailureInspectionView,
    InstanceCardView,
    InstanceDetailView,
    LogEntryView,
    LogPaneView,
    ManualControlsView,
    OperatorConsoleState,
    PreviewPaneView,
    QueueItemView,
    QueuePaneView,
    RecordingPaneView,
    TemplateAnchorView,
    VisionWorkspaceSnapshot,
    build_console_snapshot,
    build_log_pane,
    build_manual_control_command,
    build_operator_console_state,
    build_vision_workspace_snapshot,
)

__all__ = [
    "AnchorInspectionView",
    "CalibrationPaneView",
    "ConsoleSnapshot",
    "FailureInspectionView",
    "InstanceCardView",
    "InstanceDetailView",
    "LogEntryView",
    "LogPaneView",
    "ManualControlsView",
    "OperatorConsoleState",
    "PreviewPaneView",
    "QueueItemView",
    "QueuePaneView",
    "RecordingPaneView",
    "TemplateAnchorView",
    "VisionWorkspaceSnapshot",
    "build_console_snapshot",
    "build_log_pane",
    "build_manual_control_command",
    "build_operator_console_state",
    "build_vision_workspace_snapshot",
]

