"""GUI shell package."""

from roxauto.app.runtime_bridge import OperatorConsoleRuntimeBridge
from roxauto.app.viewmodels import (
    AnchorInspectionView,
    CalibrationPaneView,
    ConsoleSummaryView,
    ConsoleSnapshot,
    FailureInspectionView,
    InstanceCardView,
    InstanceDetailView,
    InstanceListEntryView,
    LogEntryView,
    LogPaneView,
    ManualControlsView,
    OperatorConsoleState,
    PreviewPaneView,
    QueueItemView,
    QueuePaneView,
    RecordingPaneView,
    TemplateAnchorView,
    VisionWorkspaceSnapshot,
    build_console_summary,
    build_console_snapshot,
    build_console_snapshot_from_runtime,
    build_instance_list_rows,
    build_log_pane,
    build_manual_control_command,
    build_operator_console_state,
    build_vision_workspace_snapshot,
)

__all__ = [
    "AnchorInspectionView",
    "CalibrationPaneView",
    "ConsoleSummaryView",
    "ConsoleSnapshot",
    "FailureInspectionView",
    "InstanceCardView",
    "InstanceDetailView",
    "InstanceListEntryView",
    "LogEntryView",
    "LogPaneView",
    "ManualControlsView",
    "OperatorConsoleState",
    "OperatorConsoleRuntimeBridge",
    "PreviewPaneView",
    "QueueItemView",
    "QueuePaneView",
    "RecordingPaneView",
    "TemplateAnchorView",
    "VisionWorkspaceSnapshot",
    "build_console_summary",
    "build_console_snapshot",
    "build_console_snapshot_from_runtime",
    "build_instance_list_rows",
    "build_log_pane",
    "build_manual_control_command",
    "build_operator_console_state",
    "build_vision_workspace_snapshot",
]

